// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AcceptInviteRequest
 */
export type AcceptInviteRequest = {
    /**
     * Token
     */
    token: string;
};

/**
 * ActionType
 */
export type ActionType = 'refund' | 'cancellation' | 'ticket';

/**
 * ActorType
 *
 * Who performed an action.
 */
export type ActorType = 'user' | 'api_key' | 'system';

/**
 * AdyenConnectorCredentials
 */
export type AdyenConnectorCredentials = {
    /**
     * Merchant Account
     *
     * Your Adyen merchant account code.
     */
    merchant_account: string;
    /**
     * Hmac Key
     *
     * The HMAC key from your Adyen standard-webhook config.
     */
    hmac_key: string;
};

/**
 * ApiKey
 *
 * An organization API key. The secret itself is never returned after creation.
 */
export type ApiKey = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Prefix
     */
    prefix: string;
    /**
     * Scopes
     */
    scopes?: Array<ApiKeyScope>;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Expires At
     */
    expires_at?: string | null;
    /**
     * Last Used At
     */
    last_used_at?: string | null;
    /**
     * Revoked At
     */
    revoked_at?: string | null;
};

/**
 * ApiKeyCreate
 */
export type ApiKeyCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Scopes
     *
     * Capabilities to grant. Defaults to all scopes.
     */
    scopes?: Array<ApiKeyScope> | null;
    /**
     * Expires In Days
     *
     * Optional automatic expiry, in days.
     */
    expires_in_days?: number | null;
};

/**
 * ApiKeyCreated
 */
export type ApiKeyCreated = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Prefix
     */
    prefix: string;
    /**
     * Scopes
     */
    scopes?: Array<ApiKeyScope>;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Expires At
     */
    expires_at?: string | null;
    /**
     * Last Used At
     */
    last_used_at?: string | null;
    /**
     * Revoked At
     */
    revoked_at?: string | null;
    /**
     * Key
     *
     * The secret key, shown once. Store it securely now.
     */
    key: string;
};

/**
 * ApiKeyScope
 *
 * A capability an API key can grant (least privilege).
 */
export type ApiKeyScope = 'verifications:write' | 'verifications:read';

/**
 * Approval
 *
 * A trusted approval for an operation, recorded by a manager.
 */
export type Approval = {
    /**
     * Id
     */
    id: string;
    /**
     * Operation Id
     */
    operation_id: string;
    /**
     * Max Amount Cents
     */
    max_amount_cents?: number | null;
    /**
     * Reason
     */
    reason?: string | null;
    /**
     * Approved By
     */
    approved_by?: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Expires At
     */
    expires_at?: string | null;
    /**
     * Revoked At
     */
    revoked_at?: string | null;
};

/**
 * ApprovalCreate
 */
export type ApprovalCreate = {
    /**
     * Operation Id
     */
    operation_id: string;
    /**
     * Max Amount Cents
     *
     * Cap the approval to this amount. None = any amount.
     */
    max_amount_cents?: number | null;
    /**
     * Reason
     */
    reason?: string | null;
    /**
     * Expires In Hours
     *
     * Optional automatic expiry, in hours.
     */
    expires_in_hours?: number | null;
};

/**
 * AuditBadge
 *
 * A signed, shareable summary of an audit run, tamper-evident, no PII.
 *
 * The signature covers the canonical body (type, label, account_ref, connector,
 * sampled, verified_completion_rate, issued_at) and is verifiable with the public
 * signing key, so a published badge can't be forged or inflated.
 */
export type AuditBadge = {
    /**
     * Label
     */
    label?: string | null;
    /**
     * Account Ref
     */
    account_ref: string;
    /**
     * Connector
     */
    connector: string;
    /**
     * Sampled
     */
    sampled: number;
    /**
     * Verified Completion Rate
     *
     * verified / sampled, in the range 0.0-1.0.
     */
    verified_completion_rate: number;
    /**
     * Issued At
     */
    issued_at: string;
    /**
     * Algorithm
     */
    algorithm?: string;
    /**
     * Signing Key Id
     */
    signing_key_id: string;
    /**
     * Signature
     */
    signature: string;
};

/**
 * AuditEvent
 *
 * An append-only record of something that happened in an organization.
 */
export type AuditEvent = {
    /**
     * Id
     */
    id: string;
    /**
     * Action
     */
    action: string;
    actor_type: ActorType;
    /**
     * Actor Id
     */
    actor_id?: string | null;
    /**
     * Target Type
     */
    target_type?: string | null;
    /**
     * Target Id
     */
    target_id?: string | null;
    /**
     * Meta
     */
    meta?: {
        [key: string]: unknown;
    } | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Prev Hash
     */
    prev_hash?: string | null;
    /**
     * Hash
     */
    hash?: string | null;
};

/**
 * AuditFinding
 *
 * One sampled action and how the audit classified it. PII-free by construction.
 */
export type AuditFinding = {
    /**
     * Refund Id
     */
    refund_id: string;
    /**
     * Charge Id
     */
    charge_id?: string | null;
    /**
     * Amount Cents
     */
    amount_cents: number;
    /**
     * Currency
     */
    currency?: string | null;
    /**
     * Status
     */
    status: string;
    result: VerificationResult;
    /**
     * Detail
     */
    detail: string;
};

/**
 * AuditReport
 *
 * The result of a read-only VCR audit. Stateless, nothing here is persisted.
 */
export type AuditReport = {
    /**
     * Connector
     */
    connector: string;
    /**
     * Account Ref
     */
    account_ref: string;
    /**
     * Sampled
     */
    sampled: number;
    vcr: VcrSummary;
    /**
     * Findings
     */
    findings: Array<AuditFinding>;
    badge: AuditBadge;
    /**
     * Generated At
     */
    generated_at: string;
};

/**
 * AuditRequest
 *
 * A free, read-only VCR audit of an organization's recent refunds.
 *
 * The credential is used once to sample the system of record and is never stored.
 */
export type AuditRequest = {
    /**
     * Connector
     */
    connector?: 'stripe';
    /**
     * Api Key
     *
     * A read-only Stripe (restricted) API key. Used once, never stored.
     */
    api_key: string;
    /**
     * Limit
     *
     * How many recent refunds to sample (max 100).
     */
    limit?: number;
    /**
     * Agent Label
     *
     * Optional label shown on the shareable badge.
     */
    agent_label?: string | null;
};

/**
 * BillingSession
 */
export type BillingSession = {
    /**
     * Url
     */
    url: string;
};

/**
 * BillingState
 *
 * An organization's billing status and usage this period.
 */
export type BillingState = {
    /**
     * Enabled
     *
     * Whether billing is configured on the server.
     */
    enabled: boolean;
    /**
     * Status
     */
    status?: string;
    /**
     * Plan
     */
    plan?: string | null;
    /**
     * Usage This Period
     */
    usage_this_period?: number;
    /**
     * Current Period End
     */
    current_period_end?: string | null;
    /**
     * Cancel At Period End
     */
    cancel_at_period_end?: boolean;
    /**
     * Free Allowance
     */
    free_allowance?: number;
    /**
     * Trial Used
     */
    trial_used?: number;
    /**
     * Entitled
     */
    entitled?: boolean;
};

/**
 * BraintreeConnectorCredentials
 */
export type BraintreeConnectorCredentials = {
    /**
     * Public Key
     */
    public_key: string;
    /**
     * Private Key
     */
    private_key: string;
};

/**
 * CancellationClaim
 *
 * An agent's claim that it cancelled a subscription.
 */
export type CancellationClaim = {
    /**
     * Subscription Id
     *
     * The subscription the agent claims it cancelled.
     */
    subscription_id: string;
    /**
     * Customer
     *
     * Customer id or email the subscription belongs to.
     */
    customer: string;
    /**
     * Idempotency Key
     */
    idempotency_key?: string | null;
    /**
     * Metadata
     *
     * Free-form context for policy checks.
     */
    metadata?: {
        [key: string]: unknown;
    } | null;
};

/**
 * CheckoutRequest
 */
export type CheckoutRequest = {
    /**
     * Success Url
     */
    success_url: string;
    /**
     * Cancel Url
     */
    cancel_url: string;
};

/**
 * ConnectorHealth
 *
 * The result of re-validating a stored connector against its provider on demand.
 */
export type ConnectorHealth = {
    type: ConnectorType;
    /**
     * Status
     *
     * ok = the credential still authenticates, invalid = the provider rejected it (revoked or rotated), unavailable = the provider couldn't be reached (transient).
     */
    status: 'ok' | 'invalid' | 'unavailable';
};

/**
 * ConnectorInfo
 *
 * A configured organization connector, the secret credentials are never returned.
 */
export type ConnectorInfo = {
    type: ConnectorType;
    /**
     * Account Ref
     *
     * Stable, non-secret fingerprint of the account.
     */
    account_ref: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * ConnectorName
 */
export type ConnectorName = 'stripe' | 'zendesk' | 'gorgias' | 'intercom' | 'shopify' | 'hubspot' | 'front' | 'servicenow' | 'salesforce' | 'netsuite' | 'square' | 'paypal' | 'braintree' | 'quickbooks' | 'adyen' | 'relay' | 'mock';

/**
 * ConnectorType
 *
 * A configurable per-org system-of-record connector (excludes the dev mock).
 */
export type ConnectorType = 'stripe' | 'zendesk' | 'gorgias' | 'intercom' | 'shopify' | 'hubspot' | 'front' | 'servicenow' | 'salesforce' | 'netsuite' | 'square' | 'paypal' | 'braintree' | 'quickbooks' | 'adyen';

/**
 * ConsistencyProof
 *
 * Proof that the log at `second_size` is an append-only extension of the log at
 * `first_size`, same leaves 0..first_size, nothing removed or rewritten (RFC 6962
 * §2.1.2). A holder of an earlier signed tree head uses it to confirm the operator
 * never forked or back-dated the log.
 */
export type ConsistencyProof = {
    /**
     * First Size
     *
     * Size of the earlier tree head being checked.
     */
    first_size: number;
    /**
     * Second Size
     *
     * Size of the later (current) tree head.
     */
    second_size: number;
    /**
     * First Root
     *
     * Hex Merkle root at first_size (RFC 6962).
     */
    first_root: string;
    /**
     * Second Root
     *
     * Hex Merkle root at second_size.
     */
    second_root: string;
    /**
     * Proof
     *
     * Hex consistency-path node hashes.
     */
    proof: Array<string>;
    /**
     * Signed tree head for second_size.
     */
    sth: SignedTreeHead;
};

/**
 * ContractRef
 *
 * Which versioned Outcome Contract a verification was judged by. The digest
 * covers the contract's canonical JSON (see GET /v1/contracts). It becomes part
 * of the receipt's signed body in receipt v3.
 */
export type ContractRef = {
    /**
     * Name
     */
    name: string;
    /**
     * Version
     */
    version: string;
    /**
     * Digest
     */
    digest: string;
};

/**
 * ContractStatus
 */
export type ContractStatus = 'preserved' | 'mismatched' | 'expired' | 'signature_invalid' | 'not_registered';

/**
 * ContractValidation
 */
export type ContractValidation = {
    type: ObservationContractType;
    status: ContractStatus;
    /**
     * Detail
     */
    detail: string;
};

/**
 * CorrelationMethod
 *
 * How the claimed action was located in the system of record.
 */
export type CorrelationMethod = 'provider_object_id' | 'none';

/**
 * CorrelationStrength
 *
 * How strong the link is between the claim and the observed record. High-risk
 * decisions should require `deterministic`. A heuristic link must never be
 * presented as certainty.
 */
export type CorrelationStrength = 'deterministic' | 'heuristic' | 'uncorrelatable';

/**
 * CurrentOrg
 *
 * The caller's organization and their role in it.
 */
export type CurrentOrg = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    role: Role;
};

/**
 * EnvelopeAccepted
 */
export type EnvelopeAccepted = {
    /**
     * Accepted
     */
    accepted?: boolean;
    /**
     * Observation Id
     */
    observation_id: string;
};

/**
 * EvidenceExport
 *
 * A portable, signed audit-evidence bundle for an organization. Helps create
 * audit evidence: every part is independently verifiable, the signed receipts,
 * the tamper-evident (hash-chained) audit log, and the transparency-log inclusion
 * proofs, and the signed manifest binds them together.
 */
export type EvidenceExport = {
    manifest: EvidenceManifest;
    /**
     * Verifications
     */
    verifications: Array<Verification>;
    /**
     * Audit Events
     */
    audit_events: Array<AuditEvent>;
    transparency_sth: SignedTreeHead;
    /**
     * Inclusion Proofs
     */
    inclusion_proofs: Array<InclusionProof>;
};

/**
 * EvidenceManifest
 *
 * A signed summary binding an evidence export to its contents, so the bundle
 * can't be added to, trimmed, or swapped without breaking the signature.
 */
export type EvidenceManifest = {
    /**
     * Type
     */
    type?: string;
    /**
     * Org Id
     */
    org_id?: string | null;
    /**
     * Generated At
     */
    generated_at: string;
    /**
     * Verification Count
     */
    verification_count: number;
    vcr: VcrSummary;
    /**
     * Audit Chain Intact
     *
     * Whether the org's audit hash chain verified.
     */
    audit_chain_intact: boolean;
    /**
     * Transparency Tree Size
     */
    transparency_tree_size: number;
    /**
     * Transparency Root
     *
     * Hex Merkle root of the transparency log at export.
     */
    transparency_root: string;
    /**
     * Content Digest
     *
     * SHA-256 hex over the bundle's receipts (sorted id+signature).
     */
    content_digest: string;
    /**
     * Algorithm
     */
    algorithm?: string;
    /**
     * Signing Key Id
     */
    signing_key_id: string;
    /**
     * Signature
     */
    signature: string;
};

/**
 * FrontConnectorCredentials
 */
export type FrontConnectorCredentials = {
    /**
     * Api Token
     */
    api_token: string;
};

/**
 * GorgiasConnectorCredentials
 */
export type GorgiasConnectorCredentials = {
    /**
     * Subdomain
     *
     * The subdomain, e.g. acme for acme.gorgias.com.
     */
    subdomain: string;
    /**
     * Email
     */
    email: string;
    /**
     * Api Key
     */
    api_key: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Health
 */
export type Health = {
    /**
     * Status
     */
    status?: string;
    /**
     * Service
     */
    service?: string;
    /**
     * Version
     */
    version: string;
};

/**
 * HubSpotConnectorCredentials
 */
export type HubSpotConnectorCredentials = {
    /**
     * Access Token
     */
    access_token: string;
};

/**
 * InclusionProof
 *
 * Proof that a receipt is included in the transparency log at a given tree size:
 * a Merkle audit path from the receipt's leaf up to the signed root.
 */
export type InclusionProof = {
    /**
     * Receipt Id
     */
    receipt_id: string;
    /**
     * Leaf Index
     *
     * 0-based position of the receipt in the log.
     */
    leaf_index: number;
    /**
     * Leaf Hash
     *
     * Hex RFC 6962 leaf hash = SHA256(0x00 || id || 0x0a || sig).
     */
    leaf_hash: string;
    /**
     * Tree Size
     */
    tree_size: number;
    /**
     * Audit Path
     *
     * Hex sibling hashes, deepest first.
     */
    audit_path: Array<string>;
    sth: SignedTreeHead;
};

/**
 * IntercomConnectorCredentials
 */
export type IntercomConnectorCredentials = {
    /**
     * Access Token
     */
    access_token: string;
};

/**
 * Invite
 *
 * A pending invitation to join an organization (shared as a link).
 */
export type Invite = {
    /**
     * Id
     */
    id: string;
    role: Role;
    /**
     * Token
     */
    token: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Accepted
     */
    accepted?: boolean;
};

/**
 * InviteCreate
 */
export type InviteCreate = {
    role?: Role;
};

/**
 * Member
 *
 * A member of an organization.
 */
export type Member = {
    /**
     * User Id
     */
    user_id: string;
    /**
     * Email
     */
    email?: string | null;
    role: Role;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Is Self
     */
    is_self?: boolean;
};

/**
 * MemberRoleUpdate
 */
export type MemberRoleUpdate = {
    role: Role;
};

/**
 * NetSuiteConnectorCredentials
 */
export type NetSuiteConnectorCredentials = {
    /**
     * Account
     *
     * The account id in URL host form, e.g. 1234567 or 1234567-sb1.
     */
    account: string;
    /**
     * Access Token
     *
     * An OAuth 2.0 bearer token.
     */
    access_token: string;
};

/**
 * ObservationContract
 *
 * A registered contract, a digest commitment, no secret material.
 */
export type ObservationContract = {
    type: ObservationContractType;
    /**
     * Digest
     *
     * SHA-256 hex of the artifact value (one-way, not the value).
     */
    digest: string;
    /**
     * Expires At
     */
    expires_at?: string | null;
    /**
     * Has Signature
     */
    has_signature?: boolean;
    /**
     * Algorithm
     */
    algorithm?: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * ObservationContractInput
 *
 * An artifact to register. Only its digest is stored, never the value itself.
 */
export type ObservationContractInput = {
    type: ObservationContractType;
    /**
     * Value
     *
     * The artifact value. Stored only as a digest.
     */
    value: string;
    /**
     * Expires At
     *
     * For session_token: when it expires (tracked, validated).
     */
    expires_at?: string | null;
    /**
     * Signature
     *
     * For webhook_payload: the HMAC to verify later, hex.
     */
    signature?: string | null;
    /**
     * Algorithm
     *
     * HMAC algorithm for webhook_payload.
     */
    algorithm?: string;
};

/**
 * ObservationContractType
 *
 * A fragile operation artifact whose integrity Postcept preserves across an
 * operation's retries, branches, and handoffs.
 */
export type ObservationContractType = 'idempotency_key' | 'oauth_state' | 'signed_url' | 'session_token' | 'webhook_payload' | 'operation_id';

/**
 * ObservationEnvelope
 */
export type ObservationEnvelope = {
    /**
     * Schema Version
     */
    schema_version: string;
    /**
     * Observation Id
     */
    observation_id: string;
    /**
     * Operation Id
     */
    operation_id: string;
    /**
     * Org Id
     */
    org_id: string;
    /**
     * Relay Id
     */
    relay_id: string;
    /**
     * Connector
     */
    connector: string;
    /**
     * Connector Version
     */
    connector_version: string;
    /**
     * Observed At
     */
    observed_at: string;
    /**
     * Nonce
     */
    nonce: string;
    facts: RefundFacts;
    /**
     * Relay Key Id
     */
    relay_key_id: string;
    /**
     * Signature
     */
    signature: string;
};

/**
 * ObservationValidateInput
 */
export type ObservationValidateInput = {
    type: ObservationContractType;
    /**
     * Value
     */
    value: string;
    /**
     * Secret
     *
     * For webhook_payload: the HMAC secret. Used once, never stored.
     */
    secret?: string | null;
};

/**
 * ObservedAuditRequest
 *
 * A VCR audit over refunds the caller has already read themselves.
 *
 * The credential never reaches Postcept: the relay reads the system of record
 * inside your environment and sends only these facts. Postcept scores them and
 * signs the badge.
 */
export type ObservedAuditRequest = {
    /**
     * Connector
     */
    connector?: 'stripe';
    /**
     * Account Ref
     *
     * A stable, non-secret fingerprint of the audited account.
     */
    account_ref: string;
    /**
     * Refunds
     *
     * Recent refunds, most recent first.
     */
    refunds: Array<ObservedRefund>;
    /**
     * Agent Label
     *
     * Optional label shown on the shareable badge.
     */
    agent_label?: string | null;
};

/**
 * ObservedRefund
 *
 * A refund as it was read out of the system of record, by something that already
 * holds the credential. Carries no customer identity and no credential.
 */
export type ObservedRefund = {
    /**
     * Refund Id
     */
    refund_id: string;
    /**
     * Charge Id
     */
    charge_id?: string | null;
    /**
     * Amount Cents
     */
    amount_cents: number;
    /**
     * Currency
     */
    currency?: string | null;
    /**
     * Status
     */
    status: string;
    /**
     * Operation Ref
     *
     * The operation this refund belongs to, used to detect a double refund.
     */
    operation_ref?: string | null;
};

/**
 * OperationContext
 *
 * The preserved observation contracts for one operation.
 */
export type OperationContext = {
    /**
     * Operation Id
     */
    operation_id: string;
    /**
     * Contracts
     */
    contracts: Array<ObservationContract>;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * OperationContextRegister
 */
export type OperationContextRegister = {
    /**
     * Contracts
     */
    contracts: Array<ObservationContractInput>;
};

/**
 * OperationContextValidateRequest
 */
export type OperationContextValidateRequest = {
    /**
     * Contracts
     */
    contracts: Array<ObservationValidateInput>;
};

/**
 * OperationContextValidation
 */
export type OperationContextValidation = {
    /**
     * Operation Id
     */
    operation_id: string;
    /**
     * Intact
     *
     * True iff every presented contract is preserved.
     */
    intact: boolean;
    /**
     * Results
     */
    results: Array<ContractValidation>;
};

/**
 * OrgUpdate
 *
 * Editable organization fields.
 */
export type OrgUpdate = {
    /**
     * Name
     */
    name: string;
};

/**
 * PayPalConnectorCredentials
 */
export type PayPalConnectorCredentials = {
    /**
     * Client Id
     *
     * A PayPal REST app client id.
     */
    client_id: string;
    /**
     * Secret
     *
     * The PayPal REST app secret.
     */
    secret: string;
};

/**
 * PlaygroundRun
 */
export type PlaygroundRun = {
    /**
     * Synthetic
     */
    synthetic?: boolean;
    scenario: ScenarioInfo;
    /**
     * Claim
     */
    claim: {
        [key: string]: unknown;
    };
    /**
     * Source Of Truth
     */
    source_of_truth: Array<{
        [key: string]: unknown;
    }>;
    verification?: Verification | null;
    /**
     * Unreachable
     */
    unreachable?: string | null;
};

/**
 * Policy
 */
export type Policy = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    action: ActionType;
    type: PolicyType;
    /**
     * Config
     */
    config: {
        [key: string]: unknown;
    };
    /**
     * Enabled
     */
    enabled: boolean;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * PolicyCreate
 */
export type PolicyCreate = {
    /**
     * Name
     */
    name: string;
    action: ActionType;
    type: PolicyType;
    /**
     * Config
     */
    config?: {
        [key: string]: unknown;
    };
    /**
     * Enabled
     */
    enabled?: boolean;
};

/**
 * PolicyType
 *
 * A configurable policy rule applied during verification.
 */
export type PolicyType = 'max_amount' | 'require_metadata' | 'require_approval_over_amount';

/**
 * PortalRequest
 */
export type PortalRequest = {
    /**
     * Return Url
     */
    return_url: string;
};

/**
 * PostconditionCategory
 *
 * Drives classification: which kind of completion failure a check represents.
 */
export type PostconditionCategory = 'existence' | 'match' | 'state' | 'duplicate' | 'policy';

/**
 * PostconditionResult
 */
export type PostconditionResult = {
    /**
     * Name
     */
    name: string;
    category?: PostconditionCategory;
    status: PostconditionStatus;
    /**
     * Detail
     */
    detail: string;
    /**
     * Expected
     */
    expected?: string | null;
    /**
     * Actual
     */
    actual?: string | null;
};

/**
 * PostconditionStatus
 */
export type PostconditionStatus = 'passed' | 'failed' | 'skipped';

/**
 * QuickBooksConnectorCredentials
 */
export type QuickBooksConnectorCredentials = {
    /**
     * Client Id
     *
     * An Intuit app client id.
     */
    client_id: string;
    /**
     * Secret
     *
     * The Intuit app client secret.
     */
    secret: string;
    /**
     * Refresh Token
     *
     * A long-lived OAuth 2.0 refresh token.
     */
    refresh_token: string;
    /**
     * Realm Id
     *
     * The QuickBooks company (realm) id.
     */
    realm_id: string;
};

/**
 * Receipt
 *
 * A signed, tamper-evident proof of what was checked and how it classified.
 */
export type Receipt = {
    /**
     * Id
     */
    id: string;
    /**
     * Org Id
     */
    org_id?: string | null;
    /**
     * Operation Id
     */
    operation_id: string;
    /**
     * Agent Id
     */
    agent_id: string;
    action: ActionType;
    /**
     * Connectors Checked
     */
    connectors_checked: Array<string>;
    /**
     * Postconditions
     */
    postconditions: Array<PostconditionResult>;
    result: VerificationResult;
    /**
     * Issued At
     */
    issued_at: string;
    /**
     * Valid As Of
     */
    valid_as_of?: string | null;
    /**
     * Test
     */
    test?: boolean;
    /**
     * Algorithm
     */
    algorithm?: string;
    /**
     * Version
     */
    version?: string;
    /**
     * Signing Key Id
     */
    signing_key_id: string;
    /**
     * Signature
     */
    signature: string;
    /**
     * Supersedes
     */
    supersedes?: string | null;
    /**
     * Superseded By
     */
    superseded_by?: string | null;
    /**
     * Contract Digest
     */
    contract_digest?: string | null;
    /**
     * Lifecycle
     */
    lifecycle?: string | null;
    /**
     * Safe To Claim Complete
     */
    safe_to_claim_complete?: boolean | null;
    /**
     * Correlation Strength
     */
    correlation_strength?: string | null;
    /**
     * Observation Relay Id
     */
    observation_relay_id?: string | null;
    /**
     * Observation Key Id
     */
    observation_key_id?: string | null;
    /**
     * Observation Digest
     */
    observation_digest?: string | null;
    /**
     * Observation Signature
     */
    observation_signature?: string | null;
};

/**
 * ReconcileSummary
 *
 * Outcome counts from a reconciliation batch run.
 */
export type ReconcileSummary = {
    /**
     * Scanned
     */
    scanned?: number;
    /**
     * Changed
     */
    changed?: number;
    /**
     * Unchanged
     */
    unchanged?: number;
    /**
     * Unavailable
     */
    unavailable?: number;
    /**
     * Skipped
     */
    skipped?: number;
};

/**
 * RefundClaim
 *
 * An agent's claim that it refunded a charge.
 */
export type RefundClaim = {
    /**
     * Refund Id
     *
     * The refund id the agent claims it created, e.g. re_4md82k.
     */
    refund_id?: string | null;
    /**
     * Charge Id
     */
    charge_id?: string | null;
    /**
     * Amount Cents
     *
     * Refund amount in minor units (cents).
     */
    amount_cents: number;
    /**
     * Currency
     *
     * ISO 4217, e.g. usd.
     */
    currency: string;
    /**
     * Customer
     *
     * Customer id or email the refund should belong to.
     */
    customer: string;
    /**
     * Idempotency Key
     */
    idempotency_key?: string | null;
    /**
     * Metadata
     *
     * Free-form context for policy checks (approval id, reason, ...).
     */
    metadata?: {
        [key: string]: unknown;
    } | null;
};

/**
 * RefundFacts
 */
export type RefundFacts = {
    /**
     * Exists
     */
    exists: boolean;
    /**
     * Refund Id
     */
    refund_id?: string | null;
    /**
     * Charge Id
     */
    charge_id?: string | null;
    /**
     * Amount Cents
     */
    amount_cents?: number | null;
    /**
     * Currency
     */
    currency?: string | null;
    /**
     * Customer
     */
    customer?: string | null;
    /**
     * Status
     */
    status?: string | null;
    /**
     * Operation Ref
     */
    operation_ref?: string | null;
    /**
     * Duplicate Refund Ids
     */
    duplicate_refund_ids?: Array<string>;
    /**
     * Duplicates Available
     */
    duplicates_available?: boolean;
};

/**
 * RelayKey
 */
export type RelayKey = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Key Id
     */
    key_id: string;
    /**
     * Public Key
     */
    public_key: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Revoked At
     */
    revoked_at?: string | null;
};

/**
 * RelayKeyCreate
 */
export type RelayKeyCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Public Key
     *
     * Base64 raw Ed25519 PUBLIC key. The seed stays with you.
     */
    public_key: string;
};

/**
 * ReviewStatus
 *
 * Recovery workflow state for a verification.
 */
export type ReviewStatus = 'not_required' | 'open' | 'in_review' | 'resolved' | 'dismissed';

/**
 * ReviewUpdate
 *
 * Transition a verification's recovery state.
 */
export type ReviewUpdate = {
    /**
     * One of: open, in_review, resolved, dismissed.
     */
    status: ReviewStatus;
    /**
     * Note
     */
    note?: string | null;
};

/**
 * Role
 *
 * A member's role within an organization.
 */
export type Role = 'owner' | 'admin' | 'member';

/**
 * RunRequest
 */
export type RunRequest = {
    /**
     * Scenario
     */
    scenario: string;
};

/**
 * SalesforceConnectorCredentials
 */
export type SalesforceConnectorCredentials = {
    /**
     * Instance Url
     *
     * e.g. https://acme.my.salesforce.com
     */
    instance_url: string;
    /**
     * Access Token
     */
    access_token: string;
};

/**
 * ScenarioInfo
 */
export type ScenarioInfo = {
    /**
     * Id
     */
    id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Story
     */
    story: string;
};

/**
 * ServiceNowConnectorCredentials
 */
export type ServiceNowConnectorCredentials = {
    /**
     * Instance
     *
     * The instance subdomain, e.g. dev12345.
     */
    instance: string;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
};

/**
 * ShopifyConnectorCredentials
 */
export type ShopifyConnectorCredentials = {
    /**
     * Shop
     *
     * The shop subdomain, e.g. acme for acme.myshopify.com.
     */
    shop: string;
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Api Version
     */
    api_version?: string;
};

/**
 * SignedTreeHead
 *
 * A signed commitment to the whole transparency log at a point in time: the
 * Merkle root over all logged receipts, the tree size, and a timestamp. Monotonic
 * and signed, so the log can't be silently rewritten or back-dated.
 */
export type SignedTreeHead = {
    /**
     * Tree Size
     *
     * Number of receipts in the log this head covers.
     */
    tree_size: number;
    /**
     * Root Hash
     *
     * Hex SHA-256 Merkle root (RFC 6962).
     */
    root_hash: string;
    /**
     * Timestamp
     */
    timestamp: string;
    /**
     * Algorithm
     */
    algorithm?: string;
    /**
     * Signing Key Id
     */
    signing_key_id: string;
    /**
     * Signature
     *
     * Ed25519 signature over {type, tree_size, root_hash, timestamp}.
     */
    signature: string;
};

/**
 * SigningKey
 *
 * The public half of the receipt signing key, clients verify receipts with this.
 */
export type SigningKey = {
    /**
     * Algorithm
     */
    algorithm?: string;
    /**
     * Key Id
     */
    key_id: string;
    /**
     * Public Key
     *
     * Base64-encoded raw Ed25519 public key.
     */
    public_key: string;
};

/**
 * SigningKeyEntry
 *
 * A registry entry: the active key or a retired one kept for verification.
 */
export type SigningKeyEntry = {
    /**
     * Algorithm
     */
    algorithm?: string;
    /**
     * Key Id
     */
    key_id: string;
    /**
     * Public Key
     *
     * Base64-encoded raw Ed25519 public key.
     */
    public_key: string;
    status?: SigningKeyStatus;
};

/**
 * SigningKeyRegistry
 *
 * Every public key a receipt may be signed with, so rotating the signing key
 * never breaks verification of receipts the old key signed. Select the entry
 * whose key_id matches the receipt's signing_key_id.
 */
export type SigningKeyRegistry = {
    /**
     * Keys
     */
    keys: Array<SigningKeyEntry>;
};

/**
 * SigningKeyStatus
 */
export type SigningKeyStatus = 'active' | 'retired';

/**
 * SquareConnectorCredentials
 */
export type SquareConnectorCredentials = {
    /**
     * Access Token
     *
     * A Square access token.
     */
    access_token: string;
};

/**
 * StripeConnectorCredentials
 */
export type StripeConnectorCredentials = {
    /**
     * Api Key
     *
     * A Stripe (restricted, read) API key.
     */
    api_key: string;
};

/**
 * TicketClaim
 *
 * An agent's claim that it resolved a support ticket.
 */
export type TicketClaim = {
    /**
     * Ticket Id
     *
     * The support ticket the agent claims it resolved.
     */
    ticket_id: string;
    /**
     * Status
     *
     * The expected ticket status, e.g. solved.
     */
    status?: string;
    /**
     * Customer
     *
     * Requester email, if it should match.
     */
    customer?: string | null;
    /**
     * Idempotency Key
     */
    idempotency_key?: string | null;
    /**
     * Metadata
     *
     * Free-form context for policy checks.
     */
    metadata?: {
        [key: string]: unknown;
    } | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * VcrPoint
 */
export type VcrPoint = {
    /**
     * Date
     *
     * ISO date (UTC) for the bucket.
     */
    date: string;
    /**
     * Claimed
     */
    claimed: number;
    /**
     * Verified
     */
    verified: number;
    /**
     * Verified Completion Rate
     */
    verified_completion_rate: number;
};

/**
 * VcrSummary
 *
 * Verified Completion Rate, verified completions over all claimed completions.
 */
export type VcrSummary = {
    /**
     * Claimed
     */
    claimed: number;
    /**
     * Verified
     */
    verified: number;
    /**
     * Incomplete
     */
    incomplete: number;
    /**
     * Duplicated
     */
    duplicated: number;
    /**
     * Mismatched
     */
    mismatched: number;
    /**
     * Policy Failed
     */
    policy_failed: number;
    /**
     * Verified Completion Rate
     *
     * verified / claimed, in the range 0.0-1.0.
     */
    verified_completion_rate: number;
};

/**
 * VcrTimeseries
 */
export type VcrTimeseries = {
    /**
     * Points
     */
    points: Array<VcrPoint>;
};

/**
 * Verification
 */
export type Verification = {
    /**
     * Id
     */
    id: string;
    /**
     * Operation Id
     */
    operation_id: string;
    /**
     * Agent Id
     */
    agent_id: string;
    action: ActionType;
    connector: ConnectorName;
    contract: ContractRef;
    result: VerificationResult;
    lifecycle: VerificationLifecycle;
    /**
     * Safe To Claim Complete
     */
    safe_to_claim_complete: boolean;
    /**
     * Claim Reason
     */
    claim_reason: string;
    /**
     * Reversal Possible
     */
    reversal_possible?: boolean;
    correlation_method?: CorrelationMethod;
    correlation_strength?: CorrelationStrength;
    /**
     * Recommended Recovery
     */
    recommended_recovery?: string;
    /**
     * Postconditions
     */
    postconditions: Array<PostconditionResult>;
    receipt: Receipt;
    /**
     * Created At
     */
    created_at: string;
    review_status?: ReviewStatus;
    /**
     * Resolution Note
     */
    resolution_note?: string | null;
    /**
     * Resolved At
     */
    resolved_at?: string | null;
    /**
     * Test
     */
    test?: boolean;
    /**
     * Reconciled At
     */
    reconciled_at?: string | null;
    /**
     * Reconcile Count
     */
    reconcile_count?: number;
    /**
     * Next Reverify At
     *
     * The contract's evidence-freshness deadline: when this verification is next re-verified against the system of record.
     */
    next_reverify_at?: string | null;
    /**
     * Decision
     *
     * One machine-actionable word for what happened, derived from the result and the lifecycle: verified, pending, not_observed, failed, mismatched, duplicated, reversed, policy_failed, indeterminate, or unavailable.
     */
    decision?: string;
    /**
     * Observation Assurance
     *
     * How the underlying state was observed: managed (Postcept read the provider with scoped credentials), relay_attested (your relay read and signed the observation), or webhook_attested (a provider-signed webhook was verified).
     */
    observation_assurance?: string;
};

/**
 * VerificationLifecycle
 *
 * Where the observed action sits in the provider's lifecycle, separate from the
 * outcome verdict. "Refund is still pending" and "refund never happened" both
 * classify as an *incomplete* outcome, but they are different situations. The
 * lifecycle dimension tells them apart.
 */
export type VerificationLifecycle = 'unobserved' | 'observed' | 'pending_finality' | 'finalized' | 'reversed' | 'indeterminate' | 'unreachable';

/**
 * VerificationPage
 */
export type VerificationPage = {
    /**
     * Items
     */
    items: Array<Verification>;
    /**
     * Limit
     */
    limit: number;
    /**
     * Offset
     */
    offset: number;
};

/**
 * VerificationRequest
 */
export type VerificationRequest = {
    /**
     * Operation Id
     *
     * Stable id for the agent operation, across retries.
     */
    operation_id: string;
    /**
     * Agent Id
     */
    agent_id: string;
    connector?: ConnectorName;
    /**
     * Claim
     */
    claim: RefundClaim | CancellationClaim | TicketClaim;
    /**
     * Test
     *
     * Sandbox mode: verify against the deterministic mock connector instead of a live system of record. Test verifications are excluded from your Verified Completion Rate.
     */
    test?: boolean;
    /**
     * Observations
     *
     * Optional: operation artifacts to validate against this operation's preserved observation contracts. A failure adds a context_intact postcondition to the receipt.
     */
    observations?: Array<ObservationValidateInput> | null;
};

/**
 * VerificationResult
 *
 * How a claimed completion was classified against the system of record.
 */
export type VerificationResult = 'verified' | 'incomplete' | 'duplicated' | 'mismatched' | 'policy_failed';

/**
 * WebhookDelivery
 */
export type WebhookDelivery = {
    /**
     * Id
     */
    id: string;
    /**
     * Endpoint Id
     */
    endpoint_id: string;
    /**
     * Event Id
     */
    event_id: string;
    /**
     * Event Type
     */
    event_type: string;
    status: WebhookDeliveryStatus;
    /**
     * Attempts
     */
    attempts: number;
    /**
     * Last Status Code
     */
    last_status_code?: number | null;
    /**
     * Last Error
     */
    last_error?: string | null;
    /**
     * Next Attempt At
     */
    next_attempt_at?: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Delivered At
     */
    delivered_at?: string | null;
};

/**
 * WebhookDeliveryPage
 */
export type WebhookDeliveryPage = {
    /**
     * Items
     */
    items: Array<WebhookDelivery>;
    /**
     * Limit
     */
    limit: number;
    /**
     * Offset
     */
    offset: number;
};

/**
 * WebhookDeliveryStatus
 */
export type WebhookDeliveryStatus = 'pending' | 'sending' | 'delivered' | 'dead';

/**
 * WebhookEndpoint
 */
export type WebhookEndpoint = {
    /**
     * Id
     */
    id: string;
    /**
     * Url
     */
    url: string;
    /**
     * Disabled
     */
    disabled?: boolean;
    /**
     * Previous Secret Expires At
     */
    previous_secret_expires_at?: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * WebhookEndpointCreate
 *
 * Register an endpoint to receive signed lifecycle webhooks.
 */
export type WebhookEndpointCreate = {
    /**
     * Url
     */
    url: string;
};

/**
 * WebhookEndpointWithSecret
 *
 * Returned ONLY on create or rotate. The secret is never readable afterwards.
 */
export type WebhookEndpointWithSecret = {
    /**
     * Id
     */
    id: string;
    /**
     * Url
     */
    url: string;
    /**
     * Disabled
     */
    disabled?: boolean;
    /**
     * Previous Secret Expires At
     */
    previous_secret_expires_at?: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Secret
     *
     * HMAC signing secret (pcpt_whsec_...). Store it now.
     */
    secret: string;
};

/**
 * WitnessStatus
 *
 * The public witness state of the transparency log.
 */
export type WitnessStatus = {
    /**
     * State
     */
    state: 'not_requested' | 'witnessed' | 'temporarily_unavailable' | 'failed' | 'invalid';
    /**
     * Checkpoint Digest
     */
    checkpoint_digest?: string | null;
    /**
     * Tree Size
     */
    tree_size?: number | null;
    /**
     * Rekor Log Index
     */
    rekor_log_index?: number | null;
    /**
     * Bundle Url
     */
    bundle_url?: string | null;
    /**
     * Witnessed At
     */
    witnessed_at?: string | null;
    /**
     * Current
     *
     * Whether the witnessed checkpoint covers the log's current tree size.
     */
    current?: boolean;
};

/**
 * WorkflowComposeRequest
 */
export type WorkflowComposeRequest = {
    /**
     * Steps
     */
    steps: Array<WorkflowStep>;
};

/**
 * WorkflowResult
 */
export type WorkflowResult = {
    /**
     * Status
     */
    status: string;
    /**
     * Safe To Claim Complete
     */
    safe_to_claim_complete: boolean;
    /**
     * Reason
     */
    reason: string;
    /**
     * Steps
     */
    steps: Array<WorkflowStepResult>;
};

/**
 * WorkflowStep
 */
export type WorkflowStep = {
    /**
     * Id
     *
     * A name for this step within the workflow, e.g. 'refund'.
     */
    id: string;
    /**
     * Verification Id
     *
     * An existing verification to include as this step.
     */
    verification_id: string;
    /**
     * Required
     */
    required?: boolean;
    /**
     * Depends On
     *
     * Step ids this step depends on. It isn't safely complete until they are.
     */
    depends_on?: Array<string>;
};

/**
 * WorkflowStepResult
 */
export type WorkflowStepResult = {
    /**
     * Id
     */
    id: string;
    /**
     * Safe To Claim Complete
     */
    safe_to_claim_complete: boolean;
    /**
     * Premature
     */
    premature: boolean;
    /**
     * Unmet Dependencies
     */
    unmet_dependencies: Array<string>;
};

/**
 * ZendeskConnectorCredentials
 */
export type ZendeskConnectorCredentials = {
    /**
     * Subdomain
     *
     * The subdomain, e.g. acme for acme.zendesk.com.
     */
    subdomain: string;
    /**
     * Email
     */
    email: string;
    /**
     * Api Token
     */
    api_token: string;
};

export type HealthzData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/healthz';
};

export type HealthzResponses = {
    /**
     * Successful Response
     */
    200: Health;
};

export type HealthzResponse = HealthzResponses[keyof HealthzResponses];

export type ReadyzData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/readyz';
};

export type ReadyzResponses = {
    /**
     * Successful Response
     */
    200: Health;
};

export type ReadyzResponse = ReadyzResponses[keyof ReadyzResponses];

export type ListOrgsData = {
    body?: never;
    headers?: {
        /**
         * X-Postcept-Org-Id
         */
        'X-Postcept-Org-Id'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/orgs';
};

export type ListOrgsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListOrgsError = ListOrgsErrors[keyof ListOrgsErrors];

export type ListOrgsResponses = {
    /**
     * Response List Orgs
     *
     * Successful Response
     */
    200: Array<CurrentOrg>;
};

export type ListOrgsResponse = ListOrgsResponses[keyof ListOrgsResponses];

export type DeleteCurrentOrgData = {
    body?: never;
    headers?: {
        /**
         * X-Postcept-Org-Id
         */
        'X-Postcept-Org-Id'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/orgs/current';
};

export type DeleteCurrentOrgErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteCurrentOrgError = DeleteCurrentOrgErrors[keyof DeleteCurrentOrgErrors];

export type DeleteCurrentOrgResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteCurrentOrgResponse = DeleteCurrentOrgResponses[keyof DeleteCurrentOrgResponses];

export type CurrentOrgData = {
    body?: never;
    headers?: {
        /**
         * X-Postcept-Org-Id
         */
        'X-Postcept-Org-Id'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/orgs/current';
};

export type CurrentOrgErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CurrentOrgError = CurrentOrgErrors[keyof CurrentOrgErrors];

export type CurrentOrgResponses = {
    /**
     * Successful Response
     */
    200: CurrentOrg;
};

export type CurrentOrgResponse = CurrentOrgResponses[keyof CurrentOrgResponses];

export type UpdateCurrentOrgData = {
    body: OrgUpdate;
    headers?: {
        /**
         * X-Postcept-Org-Id
         */
        'X-Postcept-Org-Id'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/orgs/current';
};

export type UpdateCurrentOrgErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateCurrentOrgError = UpdateCurrentOrgErrors[keyof UpdateCurrentOrgErrors];

export type UpdateCurrentOrgResponses = {
    /**
     * Successful Response
     */
    200: CurrentOrg;
};

export type UpdateCurrentOrgResponse = UpdateCurrentOrgResponses[keyof UpdateCurrentOrgResponses];

export type ListMembersData = {
    body?: never;
    headers?: {
        /**
         * X-Postcept-Org-Id
         */
        'X-Postcept-Org-Id'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/orgs/members';
};

export type ListMembersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListMembersError = ListMembersErrors[keyof ListMembersErrors];

export type ListMembersResponses = {
    /**
     * Response List Members
     *
     * Successful Response
     */
    200: Array<Member>;
};

export type ListMembersResponse = ListMembersResponses[keyof ListMembersResponses];

export type RemoveMemberData = {
    body?: never;
    headers?: {
        /**
         * X-Postcept-Org-Id
         */
        'X-Postcept-Org-Id'?: string | null;
    };
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/v1/orgs/members/{user_id}';
};

export type RemoveMemberErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RemoveMemberError = RemoveMemberErrors[keyof RemoveMemberErrors];

export type RemoveMemberResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type RemoveMemberResponse = RemoveMemberResponses[keyof RemoveMemberResponses];

export type UpdateMemberRoleData = {
    body: MemberRoleUpdate;
    headers?: {
        /**
         * X-Postcept-Org-Id
         */
        'X-Postcept-Org-Id'?: string | null;
    };
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/v1/orgs/members/{user_id}';
};

export type UpdateMemberRoleErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateMemberRoleError = UpdateMemberRoleErrors[keyof UpdateMemberRoleErrors];

export type UpdateMemberRoleResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type UpdateMemberRoleResponse = UpdateMemberRoleResponses[keyof UpdateMemberRoleResponses];

export type ListInvitesData = {
    body?: never;
    headers?: {
        /**
         * X-Postcept-Org-Id
         */
        'X-Postcept-Org-Id'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/orgs/invites';
};

export type ListInvitesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListInvitesError = ListInvitesErrors[keyof ListInvitesErrors];

export type ListInvitesResponses = {
    /**
     * Response List Invites
     *
     * Successful Response
     */
    200: Array<Invite>;
};

export type ListInvitesResponse = ListInvitesResponses[keyof ListInvitesResponses];

export type CreateInviteData = {
    body: InviteCreate;
    headers?: {
        /**
         * X-Postcept-Org-Id
         */
        'X-Postcept-Org-Id'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/orgs/invites';
};

export type CreateInviteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateInviteError = CreateInviteErrors[keyof CreateInviteErrors];

export type CreateInviteResponses = {
    /**
     * Successful Response
     */
    201: Invite;
};

export type CreateInviteResponse = CreateInviteResponses[keyof CreateInviteResponses];

export type RevokeInviteData = {
    body?: never;
    headers?: {
        /**
         * X-Postcept-Org-Id
         */
        'X-Postcept-Org-Id'?: string | null;
    };
    path: {
        /**
         * Invite Id
         */
        invite_id: string;
    };
    query?: never;
    url: '/v1/orgs/invites/{invite_id}';
};

export type RevokeInviteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RevokeInviteError = RevokeInviteErrors[keyof RevokeInviteErrors];

export type RevokeInviteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type RevokeInviteResponse = RevokeInviteResponses[keyof RevokeInviteResponses];

export type AcceptInviteData = {
    body: AcceptInviteRequest;
    headers?: {
        /**
         * X-Postcept-Org-Id
         */
        'X-Postcept-Org-Id'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/orgs/invites/accept';
};

export type AcceptInviteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AcceptInviteError = AcceptInviteErrors[keyof AcceptInviteErrors];

export type AcceptInviteResponses = {
    /**
     * Successful Response
     */
    200: CurrentOrg;
};

export type AcceptInviteResponse = AcceptInviteResponses[keyof AcceptInviteResponses];

export type ListKeysData = {
    body?: never;
    headers?: {
        /**
         * X-Postcept-Org-Id
         */
        'X-Postcept-Org-Id'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/api-keys';
};

export type ListKeysErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListKeysError = ListKeysErrors[keyof ListKeysErrors];

export type ListKeysResponses = {
    /**
     * Response List Keys
     *
     * Successful Response
     */
    200: Array<ApiKey>;
};

export type ListKeysResponse = ListKeysResponses[keyof ListKeysResponses];

export type CreateKeyData = {
    body: ApiKeyCreate;
    headers?: {
        /**
         * X-Postcept-Org-Id
         */
        'X-Postcept-Org-Id'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/api-keys';
};

export type CreateKeyErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateKeyError = CreateKeyErrors[keyof CreateKeyErrors];

export type CreateKeyResponses = {
    /**
     * Successful Response
     */
    201: ApiKeyCreated;
};

export type CreateKeyResponse = CreateKeyResponses[keyof CreateKeyResponses];

export type RevokeKeyData = {
    body?: never;
    headers?: {
        /**
         * X-Postcept-Org-Id
         */
        'X-Postcept-Org-Id'?: string | null;
    };
    path: {
        /**
         * Key Id
         */
        key_id: string;
    };
    query?: never;
    url: '/v1/api-keys/{key_id}';
};

export type RevokeKeyErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RevokeKeyError = RevokeKeyErrors[keyof RevokeKeyErrors];

export type RevokeKeyResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type RevokeKeyResponse = RevokeKeyResponses[keyof RevokeKeyResponses];

export type ListApprovalsData = {
    body?: never;
    headers?: {
        /**
         * X-Postcept-Org-Id
         */
        'X-Postcept-Org-Id'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/approvals';
};

export type ListApprovalsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListApprovalsError = ListApprovalsErrors[keyof ListApprovalsErrors];

export type ListApprovalsResponses = {
    /**
     * Response List Approvals
     *
     * Successful Response
     */
    200: Array<Approval>;
};

export type ListApprovalsResponse = ListApprovalsResponses[keyof ListApprovalsResponses];

export type GrantApprovalData = {
    body: ApprovalCreate;
    headers?: {
        /**
         * X-Postcept-Org-Id
         */
        'X-Postcept-Org-Id'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/approvals';
};

export type GrantApprovalErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GrantApprovalError = GrantApprovalErrors[keyof GrantApprovalErrors];

export type GrantApprovalResponses = {
    /**
     * Successful Response
     */
    201: Approval;
};

export type GrantApprovalResponse = GrantApprovalResponses[keyof GrantApprovalResponses];

export type RevokeApprovalData = {
    body?: never;
    headers?: {
        /**
         * X-Postcept-Org-Id
         */
        'X-Postcept-Org-Id'?: string | null;
    };
    path: {
        /**
         * Approval Id
         */
        approval_id: string;
    };
    query?: never;
    url: '/v1/approvals/{approval_id}';
};

export type RevokeApprovalErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RevokeApprovalError = RevokeApprovalErrors[keyof RevokeApprovalErrors];

export type RevokeApprovalResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type RevokeApprovalResponse = RevokeApprovalResponses[keyof RevokeApprovalResponses];

export type ListAuditData = {
    body?: never;
    headers?: {
        /**
         * X-Postcept-Org-Id
         */
        'X-Postcept-Org-Id'?: string | null;
    };
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/v1/audit';
};

export type ListAuditErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListAuditError = ListAuditErrors[keyof ListAuditErrors];

export type ListAuditResponses = {
    /**
     * Response List Audit
     *
     * Successful Response
     */
    200: Array<AuditEvent>;
};

export type ListAuditResponse = ListAuditResponses[keyof ListAuditResponses];

export type VerifyAuditData = {
    body?: never;
    headers?: {
        /**
         * X-Postcept-Org-Id
         */
        'X-Postcept-Org-Id'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/audit/verify';
};

export type VerifyAuditErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type VerifyAuditError = VerifyAuditErrors[keyof VerifyAuditErrors];

export type VerifyAuditResponses = {
    /**
     * Response Verify Audit
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type VerifyAuditResponse = VerifyAuditResponses[keyof VerifyAuditResponses];

export type BillingStateData = {
    body?: never;
    headers?: {
        /**
         * X-Postcept-Org-Id
         */
        'X-Postcept-Org-Id'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/billing';
};

export type BillingStateErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BillingStateError = BillingStateErrors[keyof BillingStateErrors];

export type BillingStateResponses = {
    /**
     * Successful Response
     */
    200: BillingState;
};

export type BillingStateResponse = BillingStateResponses[keyof BillingStateResponses];

export type CheckoutData = {
    body: CheckoutRequest;
    headers?: {
        /**
         * X-Postcept-Org-Id
         */
        'X-Postcept-Org-Id'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/billing/checkout';
};

export type CheckoutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CheckoutError = CheckoutErrors[keyof CheckoutErrors];

export type CheckoutResponses = {
    /**
     * Successful Response
     */
    200: BillingSession;
};

export type CheckoutResponse = CheckoutResponses[keyof CheckoutResponses];

export type PortalData = {
    body: PortalRequest;
    headers?: {
        /**
         * X-Postcept-Org-Id
         */
        'X-Postcept-Org-Id'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/billing/portal';
};

export type PortalErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PortalError = PortalErrors[keyof PortalErrors];

export type PortalResponses = {
    /**
     * Successful Response
     */
    200: BillingSession;
};

export type PortalResponse = PortalResponses[keyof PortalResponses];

export type ListConnectorsData = {
    body?: never;
    headers?: {
        /**
         * X-Postcept-Org-Id
         */
        'X-Postcept-Org-Id'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/connectors';
};

export type ListConnectorsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListConnectorsError = ListConnectorsErrors[keyof ListConnectorsErrors];

export type ListConnectorsResponses = {
    /**
     * Response List Connectors
     *
     * Successful Response
     */
    200: Array<ConnectorInfo>;
};

export type ListConnectorsResponse = ListConnectorsResponses[keyof ListConnectorsResponses];

export type SetStripeData = {
    body: StripeConnectorCredentials;
    headers?: {
        /**
         * X-Postcept-Org-Id
         */
        'X-Postcept-Org-Id'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/connectors/stripe';
};

export type SetStripeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SetStripeError = SetStripeErrors[keyof SetStripeErrors];

export type SetStripeResponses = {
    /**
     * Successful Response
     */
    200: ConnectorInfo;
};

export type SetStripeResponse = SetStripeResponses[keyof SetStripeResponses];

export type SetZendeskData = {
    body: ZendeskConnectorCredentials;
    headers?: {
        /**
         * X-Postcept-Org-Id
         */
        'X-Postcept-Org-Id'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/connectors/zendesk';
};

export type SetZendeskErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SetZendeskError = SetZendeskErrors[keyof SetZendeskErrors];

export type SetZendeskResponses = {
    /**
     * Successful Response
     */
    200: ConnectorInfo;
};

export type SetZendeskResponse = SetZendeskResponses[keyof SetZendeskResponses];

export type SetGorgiasData = {
    body: GorgiasConnectorCredentials;
    headers?: {
        /**
         * X-Postcept-Org-Id
         */
        'X-Postcept-Org-Id'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/connectors/gorgias';
};

export type SetGorgiasErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SetGorgiasError = SetGorgiasErrors[keyof SetGorgiasErrors];

export type SetGorgiasResponses = {
    /**
     * Successful Response
     */
    200: ConnectorInfo;
};

export type SetGorgiasResponse = SetGorgiasResponses[keyof SetGorgiasResponses];

export type SetIntercomData = {
    body: IntercomConnectorCredentials;
    headers?: {
        /**
         * X-Postcept-Org-Id
         */
        'X-Postcept-Org-Id'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/connectors/intercom';
};

export type SetIntercomErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SetIntercomError = SetIntercomErrors[keyof SetIntercomErrors];

export type SetIntercomResponses = {
    /**
     * Successful Response
     */
    200: ConnectorInfo;
};

export type SetIntercomResponse = SetIntercomResponses[keyof SetIntercomResponses];

export type SetShopifyData = {
    body: ShopifyConnectorCredentials;
    headers?: {
        /**
         * X-Postcept-Org-Id
         */
        'X-Postcept-Org-Id'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/connectors/shopify';
};

export type SetShopifyErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SetShopifyError = SetShopifyErrors[keyof SetShopifyErrors];

export type SetShopifyResponses = {
    /**
     * Successful Response
     */
    200: ConnectorInfo;
};

export type SetShopifyResponse = SetShopifyResponses[keyof SetShopifyResponses];

export type SetHubspotData = {
    body: HubSpotConnectorCredentials;
    headers?: {
        /**
         * X-Postcept-Org-Id
         */
        'X-Postcept-Org-Id'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/connectors/hubspot';
};

export type SetHubspotErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SetHubspotError = SetHubspotErrors[keyof SetHubspotErrors];

export type SetHubspotResponses = {
    /**
     * Successful Response
     */
    200: ConnectorInfo;
};

export type SetHubspotResponse = SetHubspotResponses[keyof SetHubspotResponses];

export type SetFrontData = {
    body: FrontConnectorCredentials;
    headers?: {
        /**
         * X-Postcept-Org-Id
         */
        'X-Postcept-Org-Id'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/connectors/front';
};

export type SetFrontErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SetFrontError = SetFrontErrors[keyof SetFrontErrors];

export type SetFrontResponses = {
    /**
     * Successful Response
     */
    200: ConnectorInfo;
};

export type SetFrontResponse = SetFrontResponses[keyof SetFrontResponses];

export type SetServicenowData = {
    body: ServiceNowConnectorCredentials;
    headers?: {
        /**
         * X-Postcept-Org-Id
         */
        'X-Postcept-Org-Id'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/connectors/servicenow';
};

export type SetServicenowErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SetServicenowError = SetServicenowErrors[keyof SetServicenowErrors];

export type SetServicenowResponses = {
    /**
     * Successful Response
     */
    200: ConnectorInfo;
};

export type SetServicenowResponse = SetServicenowResponses[keyof SetServicenowResponses];

export type SetSalesforceData = {
    body: SalesforceConnectorCredentials;
    headers?: {
        /**
         * X-Postcept-Org-Id
         */
        'X-Postcept-Org-Id'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/connectors/salesforce';
};

export type SetSalesforceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SetSalesforceError = SetSalesforceErrors[keyof SetSalesforceErrors];

export type SetSalesforceResponses = {
    /**
     * Successful Response
     */
    200: ConnectorInfo;
};

export type SetSalesforceResponse = SetSalesforceResponses[keyof SetSalesforceResponses];

export type SetNetsuiteData = {
    body: NetSuiteConnectorCredentials;
    headers?: {
        /**
         * X-Postcept-Org-Id
         */
        'X-Postcept-Org-Id'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/connectors/netsuite';
};

export type SetNetsuiteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SetNetsuiteError = SetNetsuiteErrors[keyof SetNetsuiteErrors];

export type SetNetsuiteResponses = {
    /**
     * Successful Response
     */
    200: ConnectorInfo;
};

export type SetNetsuiteResponse = SetNetsuiteResponses[keyof SetNetsuiteResponses];

export type SetSquareData = {
    body: SquareConnectorCredentials;
    headers?: {
        /**
         * X-Postcept-Org-Id
         */
        'X-Postcept-Org-Id'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/connectors/square';
};

export type SetSquareErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SetSquareError = SetSquareErrors[keyof SetSquareErrors];

export type SetSquareResponses = {
    /**
     * Successful Response
     */
    200: ConnectorInfo;
};

export type SetSquareResponse = SetSquareResponses[keyof SetSquareResponses];

export type SetPaypalData = {
    body: PayPalConnectorCredentials;
    headers?: {
        /**
         * X-Postcept-Org-Id
         */
        'X-Postcept-Org-Id'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/connectors/paypal';
};

export type SetPaypalErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SetPaypalError = SetPaypalErrors[keyof SetPaypalErrors];

export type SetPaypalResponses = {
    /**
     * Successful Response
     */
    200: ConnectorInfo;
};

export type SetPaypalResponse = SetPaypalResponses[keyof SetPaypalResponses];

export type SetBraintreeData = {
    body: BraintreeConnectorCredentials;
    headers?: {
        /**
         * X-Postcept-Org-Id
         */
        'X-Postcept-Org-Id'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/connectors/braintree';
};

export type SetBraintreeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SetBraintreeError = SetBraintreeErrors[keyof SetBraintreeErrors];

export type SetBraintreeResponses = {
    /**
     * Successful Response
     */
    200: ConnectorInfo;
};

export type SetBraintreeResponse = SetBraintreeResponses[keyof SetBraintreeResponses];

export type SetQuickbooksData = {
    body: QuickBooksConnectorCredentials;
    headers?: {
        /**
         * X-Postcept-Org-Id
         */
        'X-Postcept-Org-Id'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/connectors/quickbooks';
};

export type SetQuickbooksErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SetQuickbooksError = SetQuickbooksErrors[keyof SetQuickbooksErrors];

export type SetQuickbooksResponses = {
    /**
     * Successful Response
     */
    200: ConnectorInfo;
};

export type SetQuickbooksResponse = SetQuickbooksResponses[keyof SetQuickbooksResponses];

export type SetAdyenData = {
    body: AdyenConnectorCredentials;
    headers?: {
        /**
         * X-Postcept-Org-Id
         */
        'X-Postcept-Org-Id'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/connectors/adyen';
};

export type SetAdyenErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SetAdyenError = SetAdyenErrors[keyof SetAdyenErrors];

export type SetAdyenResponses = {
    /**
     * Successful Response
     */
    200: ConnectorInfo;
};

export type SetAdyenResponse = SetAdyenResponses[keyof SetAdyenResponses];

export type DeleteConnectorData = {
    body?: never;
    headers?: {
        /**
         * X-Postcept-Org-Id
         */
        'X-Postcept-Org-Id'?: string | null;
    };
    path: {
        /**
         * Connector Type
         */
        connector_type: string;
    };
    query?: never;
    url: '/v1/connectors/{connector_type}';
};

export type DeleteConnectorErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteConnectorError = DeleteConnectorErrors[keyof DeleteConnectorErrors];

export type DeleteConnectorResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteConnectorResponse = DeleteConnectorResponses[keyof DeleteConnectorResponses];

export type RecheckData = {
    body?: never;
    headers?: {
        /**
         * X-Postcept-Org-Id
         */
        'X-Postcept-Org-Id'?: string | null;
    };
    path: {
        /**
         * Connector Type
         */
        connector_type: string;
    };
    query?: never;
    url: '/v1/connectors/{connector_type}/recheck';
};

export type RecheckErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RecheckError = RecheckErrors[keyof RecheckErrors];

export type RecheckResponses = {
    /**
     * Successful Response
     */
    200: ConnectorHealth;
};

export type RecheckResponse = RecheckResponses[keyof RecheckResponses];

export type ListPoliciesData = {
    body?: never;
    headers?: {
        /**
         * X-Postcept-Org-Id
         */
        'X-Postcept-Org-Id'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/policies';
};

export type ListPoliciesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListPoliciesError = ListPoliciesErrors[keyof ListPoliciesErrors];

export type ListPoliciesResponses = {
    /**
     * Response List Policies
     *
     * Successful Response
     */
    200: Array<Policy>;
};

export type ListPoliciesResponse = ListPoliciesResponses[keyof ListPoliciesResponses];

export type CreatePolicyData = {
    body: PolicyCreate;
    headers?: {
        /**
         * X-Postcept-Org-Id
         */
        'X-Postcept-Org-Id'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/policies';
};

export type CreatePolicyErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreatePolicyError = CreatePolicyErrors[keyof CreatePolicyErrors];

export type CreatePolicyResponses = {
    /**
     * Successful Response
     */
    201: Policy;
};

export type CreatePolicyResponse = CreatePolicyResponses[keyof CreatePolicyResponses];

export type DeletePolicyData = {
    body?: never;
    headers?: {
        /**
         * X-Postcept-Org-Id
         */
        'X-Postcept-Org-Id'?: string | null;
    };
    path: {
        /**
         * Policy Id
         */
        policy_id: string;
    };
    query?: never;
    url: '/v1/policies/{policy_id}';
};

export type DeletePolicyErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeletePolicyError = DeletePolicyErrors[keyof DeletePolicyErrors];

export type DeletePolicyResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeletePolicyResponse = DeletePolicyResponses[keyof DeletePolicyResponses];

export type ListVerificationsData = {
    body?: never;
    headers?: {
        /**
         * X-Postcept-Org-Id
         */
        'X-Postcept-Org-Id'?: string | null;
    };
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/v1/verifications';
};

export type ListVerificationsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListVerificationsError = ListVerificationsErrors[keyof ListVerificationsErrors];

export type ListVerificationsResponses = {
    /**
     * Successful Response
     */
    200: VerificationPage;
};

export type ListVerificationsResponse = ListVerificationsResponses[keyof ListVerificationsResponses];

export type CreateVerificationData = {
    body: VerificationRequest;
    headers?: {
        /**
         * Idempotency-Key
         */
        'Idempotency-Key'?: string | null;
        /**
         * X-Postcept-Org-Id
         */
        'X-Postcept-Org-Id'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/verifications';
};

export type CreateVerificationErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateVerificationError = CreateVerificationErrors[keyof CreateVerificationErrors];

export type CreateVerificationResponses = {
    /**
     * Successful Response
     */
    201: Verification;
};

export type CreateVerificationResponse = CreateVerificationResponses[keyof CreateVerificationResponses];

export type GetVerificationData = {
    body?: never;
    headers?: {
        /**
         * X-Postcept-Org-Id
         */
        'X-Postcept-Org-Id'?: string | null;
    };
    path: {
        /**
         * Verification Id
         */
        verification_id: string;
    };
    query?: never;
    url: '/v1/verifications/{verification_id}';
};

export type GetVerificationErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetVerificationError = GetVerificationErrors[keyof GetVerificationErrors];

export type GetVerificationResponses = {
    /**
     * Successful Response
     */
    200: Verification;
};

export type GetVerificationResponse = GetVerificationResponses[keyof GetVerificationResponses];

export type ReconcileVerificationData = {
    body?: never;
    headers?: {
        /**
         * X-Postcept-Org-Id
         */
        'X-Postcept-Org-Id'?: string | null;
    };
    path: {
        /**
         * Verification Id
         */
        verification_id: string;
    };
    query?: never;
    url: '/v1/verifications/{verification_id}/reconcile';
};

export type ReconcileVerificationErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReconcileVerificationError = ReconcileVerificationErrors[keyof ReconcileVerificationErrors];

export type ReconcileVerificationResponses = {
    /**
     * Successful Response
     */
    200: Verification;
};

export type ReconcileVerificationResponse = ReconcileVerificationResponses[keyof ReconcileVerificationResponses];

export type RunReconciliationData = {
    body?: never;
    headers?: {
        /**
         * X-Postcept-Org-Id
         */
        'X-Postcept-Org-Id'?: string | null;
    };
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/v1/reconcile/run';
};

export type RunReconciliationErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RunReconciliationError = RunReconciliationErrors[keyof RunReconciliationErrors];

export type RunReconciliationResponses = {
    /**
     * Successful Response
     */
    200: ReconcileSummary;
};

export type RunReconciliationResponse = RunReconciliationResponses[keyof RunReconciliationResponses];

export type GetReceiptData = {
    body?: never;
    headers?: {
        /**
         * X-Postcept-Org-Id
         */
        'X-Postcept-Org-Id'?: string | null;
    };
    path: {
        /**
         * Receipt Id
         */
        receipt_id: string;
    };
    query?: never;
    url: '/v1/receipts/{receipt_id}';
};

export type GetReceiptErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetReceiptError = GetReceiptErrors[keyof GetReceiptErrors];

export type GetReceiptResponses = {
    /**
     * Successful Response
     */
    200: Receipt;
};

export type GetReceiptResponse = GetReceiptResponses[keyof GetReceiptResponses];

export type ListRecoveryData = {
    body?: never;
    headers?: {
        /**
         * X-Postcept-Org-Id
         */
        'X-Postcept-Org-Id'?: string | null;
    };
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/v1/recovery';
};

export type ListRecoveryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListRecoveryError = ListRecoveryErrors[keyof ListRecoveryErrors];

export type ListRecoveryResponses = {
    /**
     * Successful Response
     */
    200: VerificationPage;
};

export type ListRecoveryResponse = ListRecoveryResponses[keyof ListRecoveryResponses];

export type UpdateReviewData = {
    body: ReviewUpdate;
    headers?: {
        /**
         * X-Postcept-Org-Id
         */
        'X-Postcept-Org-Id'?: string | null;
    };
    path: {
        /**
         * Verification Id
         */
        verification_id: string;
    };
    query?: never;
    url: '/v1/verifications/{verification_id}/review';
};

export type UpdateReviewErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateReviewError = UpdateReviewErrors[keyof UpdateReviewErrors];

export type UpdateReviewResponses = {
    /**
     * Successful Response
     */
    200: Verification;
};

export type UpdateReviewResponse = UpdateReviewResponses[keyof UpdateReviewResponses];

export type VerifiedCompletionRateData = {
    body?: never;
    headers?: {
        /**
         * X-Postcept-Org-Id
         */
        'X-Postcept-Org-Id'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/metrics/vcr';
};

export type VerifiedCompletionRateErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type VerifiedCompletionRateError = VerifiedCompletionRateErrors[keyof VerifiedCompletionRateErrors];

export type VerifiedCompletionRateResponses = {
    /**
     * Successful Response
     */
    200: VcrSummary;
};

export type VerifiedCompletionRateResponse = VerifiedCompletionRateResponses[keyof VerifiedCompletionRateResponses];

export type VcrTimeseriesData = {
    body?: never;
    headers?: {
        /**
         * X-Postcept-Org-Id
         */
        'X-Postcept-Org-Id'?: string | null;
    };
    path?: never;
    query?: {
        /**
         * Days
         */
        days?: number;
    };
    url: '/v1/metrics/vcr/timeseries';
};

export type VcrTimeseriesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type VcrTimeseriesError = VcrTimeseriesErrors[keyof VcrTimeseriesErrors];

export type VcrTimeseriesResponses = {
    /**
     * Successful Response
     */
    200: VcrTimeseries;
};

export type VcrTimeseriesResponse = VcrTimeseriesResponses[keyof VcrTimeseriesResponses];

export type SigningKeyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/signing-key';
};

export type SigningKeyResponses = {
    /**
     * Successful Response
     */
    200: SigningKey;
};

export type SigningKeyResponse = SigningKeyResponses[keyof SigningKeyResponses];

export type ConnectorAssuranceData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/connectors/assurance';
};

export type ConnectorAssuranceResponses = {
    /**
     * Response Connector Assurance
     *
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type ConnectorAssuranceResponse = ConnectorAssuranceResponses[keyof ConnectorAssuranceResponses];

export type ListContractsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/contracts';
};

export type ListContractsResponses = {
    /**
     * Response List Contracts
     *
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type ListContractsResponse = ListContractsResponses[keyof ListContractsResponses];

export type SigningKeysData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/signing-keys';
};

export type SigningKeysResponses = {
    /**
     * Successful Response
     */
    200: SigningKeyRegistry;
};

export type SigningKeysResponse = SigningKeysResponses[keyof SigningKeysResponses];

export type RunObservedAuditData = {
    body: ObservedAuditRequest;
    path?: never;
    query?: never;
    url: '/v1/vcr-audit/observed';
};

export type RunObservedAuditErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RunObservedAuditError = RunObservedAuditErrors[keyof RunObservedAuditErrors];

export type RunObservedAuditResponses = {
    /**
     * Successful Response
     */
    200: AuditReport;
};

export type RunObservedAuditResponse = RunObservedAuditResponses[keyof RunObservedAuditResponses];

export type RunVcrAuditData = {
    body: AuditRequest;
    path?: never;
    query?: never;
    url: '/v1/vcr-audit';
};

export type RunVcrAuditErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RunVcrAuditError = RunVcrAuditErrors[keyof RunVcrAuditErrors];

export type RunVcrAuditResponses = {
    /**
     * Successful Response
     */
    200: AuditReport;
};

export type RunVcrAuditResponse = RunVcrAuditResponses[keyof RunVcrAuditResponses];

export type GetSthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/transparency/sth';
};

export type GetSthResponses = {
    /**
     * Successful Response
     */
    200: SignedTreeHead;
};

export type GetSthResponse = GetSthResponses[keyof GetSthResponses];

export type GetProofData = {
    body?: never;
    path: {
        /**
         * Receipt Id
         */
        receipt_id: string;
    };
    query?: never;
    url: '/v1/transparency/proof/{receipt_id}';
};

export type GetProofErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetProofError = GetProofErrors[keyof GetProofErrors];

export type GetProofResponses = {
    /**
     * Successful Response
     */
    200: InclusionProof;
};

export type GetProofResponse = GetProofResponses[keyof GetProofResponses];

export type GetConsistencyData = {
    body?: never;
    path?: never;
    query: {
        /**
         * First
         */
        first: number;
        /**
         * Second
         */
        second?: number | null;
    };
    url: '/v1/transparency/consistency';
};

export type GetConsistencyErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetConsistencyError = GetConsistencyErrors[keyof GetConsistencyErrors];

export type GetConsistencyResponses = {
    /**
     * Successful Response
     */
    200: ConsistencyProof;
};

export type GetConsistencyResponse = GetConsistencyResponses[keyof GetConsistencyResponses];

export type GetWitnessData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/transparency/witness';
};

export type GetWitnessResponses = {
    /**
     * Successful Response
     */
    200: WitnessStatus;
};

export type GetWitnessResponse = GetWitnessResponses[keyof GetWitnessResponses];

export type ExportEvidenceData = {
    body?: never;
    headers?: {
        /**
         * X-Postcept-Org-Id
         */
        'X-Postcept-Org-Id'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/evidence/export';
};

export type ExportEvidenceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ExportEvidenceError = ExportEvidenceErrors[keyof ExportEvidenceErrors];

export type ExportEvidenceResponses = {
    /**
     * Successful Response
     */
    200: EvidenceExport;
};

export type ExportEvidenceResponse = ExportEvidenceResponses[keyof ExportEvidenceResponses];

export type GetObservationsData = {
    body?: never;
    headers?: {
        /**
         * X-Postcept-Org-Id
         */
        'X-Postcept-Org-Id'?: string | null;
    };
    path: {
        /**
         * Operation Id
         */
        operation_id: string;
    };
    query?: never;
    url: '/v1/operations/{operation_id}/observations';
};

export type GetObservationsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetObservationsError = GetObservationsErrors[keyof GetObservationsErrors];

export type GetObservationsResponses = {
    /**
     * Successful Response
     */
    200: OperationContext;
};

export type GetObservationsResponse = GetObservationsResponses[keyof GetObservationsResponses];

export type RegisterObservationsData = {
    body: OperationContextRegister;
    headers?: {
        /**
         * X-Postcept-Org-Id
         */
        'X-Postcept-Org-Id'?: string | null;
    };
    path: {
        /**
         * Operation Id
         */
        operation_id: string;
    };
    query?: never;
    url: '/v1/operations/{operation_id}/observations';
};

export type RegisterObservationsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterObservationsError = RegisterObservationsErrors[keyof RegisterObservationsErrors];

export type RegisterObservationsResponses = {
    /**
     * Successful Response
     */
    201: OperationContext;
};

export type RegisterObservationsResponse = RegisterObservationsResponses[keyof RegisterObservationsResponses];

export type ValidateObservationsData = {
    body: OperationContextValidateRequest;
    headers?: {
        /**
         * X-Postcept-Org-Id
         */
        'X-Postcept-Org-Id'?: string | null;
    };
    path: {
        /**
         * Operation Id
         */
        operation_id: string;
    };
    query?: never;
    url: '/v1/operations/{operation_id}/observations/validate';
};

export type ValidateObservationsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ValidateObservationsError = ValidateObservationsErrors[keyof ValidateObservationsErrors];

export type ValidateObservationsResponses = {
    /**
     * Successful Response
     */
    200: OperationContextValidation;
};

export type ValidateObservationsResponse = ValidateObservationsResponses[keyof ValidateObservationsResponses];

export type ListScenariosData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/playground/scenarios';
};

export type ListScenariosResponses = {
    /**
     * Response List Scenarios
     *
     * Successful Response
     */
    200: Array<ScenarioInfo>;
};

export type ListScenariosResponse = ListScenariosResponses[keyof ListScenariosResponses];

export type RunScenarioData = {
    body: RunRequest;
    path?: never;
    query?: never;
    url: '/v1/playground/verify';
};

export type RunScenarioErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RunScenarioError = RunScenarioErrors[keyof RunScenarioErrors];

export type RunScenarioResponses = {
    /**
     * Successful Response
     */
    200: PlaygroundRun;
};

export type RunScenarioResponse = RunScenarioResponses[keyof RunScenarioResponses];

export type ListRelayKeysData = {
    body?: never;
    headers?: {
        /**
         * X-Postcept-Org-Id
         */
        'X-Postcept-Org-Id'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/relay-keys';
};

export type ListRelayKeysErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListRelayKeysError = ListRelayKeysErrors[keyof ListRelayKeysErrors];

export type ListRelayKeysResponses = {
    /**
     * Response List Relay Keys
     *
     * Successful Response
     */
    200: Array<RelayKey>;
};

export type ListRelayKeysResponse = ListRelayKeysResponses[keyof ListRelayKeysResponses];

export type CreateRelayKeyData = {
    body: RelayKeyCreate;
    headers?: {
        /**
         * X-Postcept-Org-Id
         */
        'X-Postcept-Org-Id'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/relay-keys';
};

export type CreateRelayKeyErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateRelayKeyError = CreateRelayKeyErrors[keyof CreateRelayKeyErrors];

export type CreateRelayKeyResponses = {
    /**
     * Successful Response
     */
    201: RelayKey;
};

export type CreateRelayKeyResponse = CreateRelayKeyResponses[keyof CreateRelayKeyResponses];

export type RevokeRelayKeyData = {
    body?: never;
    headers?: {
        /**
         * X-Postcept-Org-Id
         */
        'X-Postcept-Org-Id'?: string | null;
    };
    path: {
        /**
         * Relay Id
         */
        relay_id: string;
    };
    query?: never;
    url: '/v1/relay-keys/{relay_id}';
};

export type RevokeRelayKeyErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RevokeRelayKeyError = RevokeRelayKeyErrors[keyof RevokeRelayKeyErrors];

export type RevokeRelayKeyResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type RevokeRelayKeyResponse = RevokeRelayKeyResponses[keyof RevokeRelayKeyResponses];

export type SubmitObservationData = {
    body: ObservationEnvelope;
    headers?: {
        /**
         * X-Postcept-Org-Id
         */
        'X-Postcept-Org-Id'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/relay/observations';
};

export type SubmitObservationErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SubmitObservationError = SubmitObservationErrors[keyof SubmitObservationErrors];

export type SubmitObservationResponses = {
    /**
     * Successful Response
     */
    202: EnvelopeAccepted;
};

export type SubmitObservationResponse = SubmitObservationResponses[keyof SubmitObservationResponses];

export type ComposeWorkflowData = {
    body: WorkflowComposeRequest;
    headers?: {
        /**
         * X-Postcept-Org-Id
         */
        'X-Postcept-Org-Id'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/workflows/compose';
};

export type ComposeWorkflowErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ComposeWorkflowError = ComposeWorkflowErrors[keyof ComposeWorkflowErrors];

export type ComposeWorkflowResponses = {
    /**
     * Successful Response
     */
    200: WorkflowResult;
};

export type ComposeWorkflowResponse = ComposeWorkflowResponses[keyof ComposeWorkflowResponses];

export type ListWebhookEndpointsData = {
    body?: never;
    headers?: {
        /**
         * X-Postcept-Org-Id
         */
        'X-Postcept-Org-Id'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/webhook-endpoints';
};

export type ListWebhookEndpointsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListWebhookEndpointsError = ListWebhookEndpointsErrors[keyof ListWebhookEndpointsErrors];

export type ListWebhookEndpointsResponses = {
    /**
     * Response List Webhook Endpoints
     *
     * Successful Response
     */
    200: Array<WebhookEndpoint>;
};

export type ListWebhookEndpointsResponse = ListWebhookEndpointsResponses[keyof ListWebhookEndpointsResponses];

export type CreateWebhookEndpointData = {
    body: WebhookEndpointCreate;
    headers?: {
        /**
         * X-Postcept-Org-Id
         */
        'X-Postcept-Org-Id'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/webhook-endpoints';
};

export type CreateWebhookEndpointErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateWebhookEndpointError = CreateWebhookEndpointErrors[keyof CreateWebhookEndpointErrors];

export type CreateWebhookEndpointResponses = {
    /**
     * Successful Response
     */
    201: WebhookEndpointWithSecret;
};

export type CreateWebhookEndpointResponse = CreateWebhookEndpointResponses[keyof CreateWebhookEndpointResponses];

export type RotateWebhookSecretData = {
    body?: never;
    headers?: {
        /**
         * X-Postcept-Org-Id
         */
        'X-Postcept-Org-Id'?: string | null;
    };
    path: {
        /**
         * Endpoint Id
         */
        endpoint_id: string;
    };
    query?: never;
    url: '/v1/webhook-endpoints/{endpoint_id}/rotate';
};

export type RotateWebhookSecretErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RotateWebhookSecretError = RotateWebhookSecretErrors[keyof RotateWebhookSecretErrors];

export type RotateWebhookSecretResponses = {
    /**
     * Successful Response
     */
    200: WebhookEndpointWithSecret;
};

export type RotateWebhookSecretResponse = RotateWebhookSecretResponses[keyof RotateWebhookSecretResponses];

export type DeleteWebhookEndpointData = {
    body?: never;
    headers?: {
        /**
         * X-Postcept-Org-Id
         */
        'X-Postcept-Org-Id'?: string | null;
    };
    path: {
        /**
         * Endpoint Id
         */
        endpoint_id: string;
    };
    query?: never;
    url: '/v1/webhook-endpoints/{endpoint_id}';
};

export type DeleteWebhookEndpointErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteWebhookEndpointError = DeleteWebhookEndpointErrors[keyof DeleteWebhookEndpointErrors];

export type DeleteWebhookEndpointResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteWebhookEndpointResponse = DeleteWebhookEndpointResponses[keyof DeleteWebhookEndpointResponses];

export type ListWebhookDeliveriesData = {
    body?: never;
    headers?: {
        /**
         * X-Postcept-Org-Id
         */
        'X-Postcept-Org-Id'?: string | null;
    };
    path?: never;
    query?: {
        /**
         * Status
         */
        status?: WebhookDeliveryStatus | null;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/v1/webhook-deliveries';
};

export type ListWebhookDeliveriesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListWebhookDeliveriesError = ListWebhookDeliveriesErrors[keyof ListWebhookDeliveriesErrors];

export type ListWebhookDeliveriesResponses = {
    /**
     * Successful Response
     */
    200: WebhookDeliveryPage;
};

export type ListWebhookDeliveriesResponse = ListWebhookDeliveriesResponses[keyof ListWebhookDeliveriesResponses];
